//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBooking.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GridColumnNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridColumnNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketBooking.Localization.GridColumnNames", typeof(GridColumnNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry ID.
        /// </summary>
        public static string EntryIdentifier {
            get {
                return ResourceManager.GetString("EntryIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry time.
        /// </summary>
        public static string EntryTime {
            get {
                return ResourceManager.GetString("EntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastbane.
        /// </summary>
        public static string Lastnane {
            get {
                return ResourceManager.GetString("Lastnane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Time (od).
        /// </summary>
        public static string LoginTime {
            get {
                return ResourceManager.GetString("LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (h:m:s).
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalPrice.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkTime.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
    }
}
